Add blog post about new release
metafacture/metafacture-blog pull request #36
Opened 2024-03-12 16:08 UTC by dr0i

Titled: "Metafacture releases: Core 6.0.0, Fix 1.0.0, Playground 1.0.0".

See https://github.com/metafacture/metafacture-core/issues/515 .

2024-03-12 16:23 UTC, blackwinter requested changes
I don't get all the monospace formatting, but it seems to be established practice in these blog posts.

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +Most remarkable is certainly the switch to `Java 11`, hence the new Major
```suggestion
Most remarkable is certainly the switch to `Java 11`, hence the new major
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> + metafacture-core-5.7.0](https://blog.metafacture.org/metafacture-5.7.0/) in November 2023.
```suggestion
 metafacture-core 5.7.0](https://blog.metafacture.org/metafacture-5.7.0/) in November 2023.
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +b) [`metafacture-fix-1.0.0`](https://github.com/metafacture/metafacture-fix/releases/tag/1.0.0).
```suggestion
b) [`metafacture-fix 1.0.0`](https://github.com/metafacture/metafacture-fix/releases/tag/1.0.0).
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +    Metamorph. Inspired by Catmandu Fix"](https://github.com/metafacture/metafacture-fix)).
```suggestion
    Metamorph, inspired by Catmandu Fix"](https://github.com/metafacture/metafacture-fix)).
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +c)  `metafacture-playground-1.0.0`.
```suggestion
c) `metafacture-playground 1.0.0`.
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +    (metafacture-playground is ["a web application to play around with Metafactures languages Fix, Flux and Morph inspired by the JSON-LD Playground"](https://github.com/metafacture/metafacture-playg
```suggestion
    (metafacture-playground is ["a web application to play around with Metafacture's languages Fix, Flux and Morph, inspired by the JSON-LD Playground"](https://github.com/metafacture/metafacture-playground/)).
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +- IO:  Fix misconception of "Content-Encoding" [#513](https://github.com/metafacture/metafacture-core/issues/513)
```suggestion
- IO: Fix misconception of "Content-Encoding" [#513](https://github.com/metafacture/metafacture-core/issues/513)
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +- Switch to Java version 11 [#518](https://github.com/metafacture/metafacture-core/issues518)
```suggestion
- Switch to Java version 11 [#518](https://github.com/metafacture/metafacture-core/issues/518)
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +- Upgrade Gradle wrapper [#283](https://github.com/metafacture/metafacture-fix/issues/302)
```suggestion
- Upgrade Gradle wrapper [#283](https://github.com/metafacture/metafacture-fix/issues/283)
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +- Switch to Java 11 [#343](https://github.com/metafacture/metafacture-fix/issues/302)
- Switch to Java 11 [#343](https://github.com/metafacture/metafacture-fix/issues/343)

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +- Add links to playground for several Fixes [#339](https://github.com/metafacture/metafacture-fix/issues/302)
- Add links to playground for several Fixes [#339](https://github.com/metafacture/metafacture-fix/issues/339)

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +## matafacture-playground
```suggestion
## metafacture-playground
```

2024-03-12 16:23 UTC, blackwinter commented on content/blog/metafacture-releases_core-6.0.0_fix-1.0.0_playground-1.0.0/index.md
> +- Clear message and result when process [#126](https://github.com/metafacture/metafacture-playground/issues/126)
- Clear message and result when processing [#126](https://github.com/metafacture/metafacture-playground/issues/126)

2024-03-13 08:54 UTC, acka47 commented
I think I will better take a look at it when @blackwinter 's suggestions are committed, @dr0i .

2024-03-14 14:05 UTC, dr0i commented
Thx for the many fixes, especially fixing the links !

2024-03-14 14:05 UTC, dr0i commented
@acka47 you can have a look now

2024-03-14 14:53 UTC, acka47 approved these changes
+1 I have removed the reference to the JSON-LD playground as there are a lot of plyaygrounds around and the JSON-LD one isn't even one of the best example, I think.

2024-03-14 15:02 UTC, merged

2024-03-14 15:07 UTC, dr0i commented
Deployed, see https://blog.metafacture.org/. Closed.